name: Pulumi Pipeline

on:
  push:
    branches:
      - main # Trigger the pipeline on 'main' branch push
  pull_request:
    branches:
      - main # Trigger on pull requests to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Set the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pulumi pulumi_aws  # Ensure Pulumi and required libraries are installed

    - name: Configure AWS Credentials (for LocalStack)
      env:
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_DEFAULT_REGION: us-east-1
      run: echo "AWS credentials configured for LocalStack"

    - name: Set Pulumi Access Token
      run: echo "PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_ACCESS_TOKEN }}" >> $GITHUB_ENV  

    - name: Set Pulumi Config Passphrase
      run: echo "PULUMI_CONFIG_PASSPHRASE=${{ secrets.PULUMI_CONFIG_PASSPHRASE }}" >> $GITHUB_ENV

    - name: Create the dev stack (if it doesn't exist)
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      run: |
        pulumi stack init dev || echo "Dev stack already exists"

    - name: Deploy resources using Pulumi
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      run: pulumi up --yes --stack dev


    - name: Run Pulumi Preview
      run: |
          pulumi preview --stack dev  # Preview the changes

    # Optional: If you want to deploy, you can run pulumi up instead
    - name: Pulumi Up (Deploy)
      run: pulumi up --yes --stack prod # Change to your stack name
