name: Pulumi Pipeline

on:
  push:
    branches:
      - main # Trigger the pipeline when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main # Trigger the pipeline when a pull request is made to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Set the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pulumi pulumi_aws  # Ensure Pulumi and required libraries are installed

    - name: Configure AWS Credentials for LocalStack
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}  # LocalStack endpoint for services like S3
      run: |
        echo "AWS credentials configured for LocalStack"
        echo "Setting LocalStack endpoint to ${AWS_ENDPOINT_URL}"

    - name: Set Pulumi Access Token
      run: echo "PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_ACCESS_TOKEN }}" >> $GITHUB_ENV  

    - name: Set Pulumi Config Passphrase
      run: echo "PULUMI_CONFIG_PASSPHRASE=${{ secrets.PULUMI_CONFIG_PASSPHRASE }}" >> $GITHUB_ENV

    - name: Create the dev stack (if it doesn't exist)
      run: |
          pulumi stack init dev || echo "Dev stack already exists"

    - name: Run Pulumi Preview
      run: pulumi preview --stack dev --non-interactive --disable-preview

    - name: Run Pulumi Up
      run: |
        pulumi up --stack dev --non-interactive --yes
